### ISSUE TITLE
Forcing globally installed elm-format

### ISSUE THREAD

**Issue by krksgbr** [gicentre/prettier-plugin-elm#10]
Hi!
In our project, `elm-format` is installed as a `nix` package. This means that in `nix-shell` we need to be able to run the instance of `elm-format` provided by `nix` instead of the one installed by `prettier-plugin-elm` as a dependency. We'd like to have a way of configuring this behavior. Not sure what the best way would be for passing in configuration, maybe through an environment variable: `PRETTIER_PLUGIN_ELM_PREFER_LOCAL=false`? Currently we solve this problem through a fork, but it would be nice to have this supported in the official package. Would you accept a PR for this?

**Comment by kachkaev** [comment]
Hi @krksgbr! I see what you're after.

How about an env variable called `PRETTIER_PLUGIN_ELM_CUSTOM_PATH_TO_ELM_FORMAT`? When it's set to something, we do this:

https://github.com/gicentre/prettier-plugin-elm/blob/bbf66dc2764ce5d2b89453420ff9745333537510/src/util.ts#L19-L26

↓

```ts
export const formatTextWithElmFormat = (text: string): string => {
  const customPathToElmFormat = process.env.PRETTIER_PLUGIN_ELM_CUSTOM_PATH_TO_ELM_FORMAT;
  return execa.sync(customPathToElmFormat || "elm-format", ["--stdin", "--elm-version=0.19"], {
    input: text,
    preferLocal: !!customPathToElmFormat,
    localDir: __dirname,
    stripEof: false,
  }).stdout;
};
```

What you'll then be able to do is:

```bash
export PRETTIER_PLUGIN_ELM_CUSTOM_PATH_TO_ELM_FORMAT=elm-format
prettier --write "**/*.elm"
```

```bash
export PRETTIER_PLUGIN_ELM_CUSTOM_PATH_TO_ELM_FORMAT=/path/to/non-global/elm-format
prettier --write "**/*.elm"
```

I'm happy to consider a PR that introduces this. It'd be great if you could add test coverage to the change. Upgrading dependencies could be also worth it given the opportunity.

---

**UPD:** Looks like cache must be made aware of the value too.

**Comment by krksgbr** [comment]
Awesome:) 
Will try and send you a PR today.

**Comment by kachkaev** [comment]
Cool. I won't be able to release at least for another week and a half, so no rush 😉

**Comment by krksgbr** [comment]
Hey @kachkaev!

In the meantime, I've had a discussion about this with @knuton. After a bit more careful consideration we came to the conclusion that the implementation proposed above would not be as useful for us as I initially thought.

Two issues we have with it are:
- It would lead to surprising behavior if one doesn't know about having to set the environment variable. 
- We're transitioning to the use of [Lorri](https://github.com/target/lorri) (`nix-shell` replacement for project development), and in the short-term, it will become a bit of a hassle to set environment variables involving `nix` paths because some functionality is still missing in Lorri.

What do you think of giving preference to the global installation of `elm-format` and falling back to the one installed by the plugin when it is not found? I feel like it would be closer to the behavior specified in the `elm-format` plugin development [guidelines](https://github.com/avh4/elm-format/issues/104).

Specifically:
> If the path to elm-format has not [been] explicitly specified by the user, the plugin should automatically find elm-format if it is located on the $PATH or in /usr/local/bin/

**Comment by kachkaev** [comment]
I see. Let’s then close this issue and reopen it if you have further thoughts.
