### ISSUE TITLE
is it possible to change to 2-space indentation?

### ISSUE THREAD

**Issue by nuu54262** [gicentre/prettier-plugin-elm#11]
Is it there any way to set the configuration to 2-space tab like we did on `prettier.config.js`?

**Comment by kachkaev** [comment]
Hi @nuu54262 👋 I'm afraid this option is out of scope of `prettier-plugin-elm` as it simply delegates formatting work to [`elm-format`](https://github.com/avh4/elm-format). This underlying tool does not have any config options, so they cannot be added to the Prettier plugin as well. See https://github.com/avh4/elm-format/pull/210 and https://github.com/avh4/elm-format/pull/289.
