### ISSUE TITLE
Formatting markdown text works but not elm code blocks

### ISSUE THREAD

**Issue by mpizenberg** [gicentre/prettier-plugin-elm#27]
I've installed VS Code with prettier and this prettier-plugin-elm and I can't figure out why only the text parts of my markdown document are formatted on save, and not the elm code blocks. Is there a way I could diagnose what is wrong? (I'm not a VS Code user)

elm version: 0.19.1
npm version: 6.14.11
vs code version: 1.61.2
prettier version: 2.3.2
prettier-plugin-elm version: ? don't know how to check, I guess the latest one.
vs code prettier extension: 9.0.0

**Comment by kachkaev** [comment]
👋 @mpizenberg! Could you please share your installation steps for `prettier` and `prettier-plugin-elm`? Globally installed packages may work differently from the local ones. Other factors may include your operating system and how your Node.js / npm is installed. It’d be also interesting to see the output of Prettier extension in VSCode when you trigger file formatting:

<img width="826" alt="Screenshot 2021-11-03 at 22 56 45" src="https://user-images.githubusercontent.com/608862/140225838-f7335bf5-3cc0-4c45-b8d7-b706b0e9745c.png">

**Comment by mpizenberg** [comment]
![image](https://user-images.githubusercontent.com/2905865/140271375-278a3a7b-bc5a-4fd8-85a3-1695373adf08.png)

There does not seem to be any problem when the formatting is triggered, so I guess it's just that it does not find the plugin.

The markdown document I'm writing is not in a JS project, so I don't have a package.json and node_modules directory. I've thus installed globally the plugin, which is located in `/home/matthieu/.config/nvm/14.15.5/lib/node_modules/prettier-plugin-elm` since I have a node installation managed by nvm (the fish one).

Also tell me if I'm wrong, but I believe the Prettier plugin for VSCode comes with its own prettier, so I would not know if it's picking up the one I have globally installed?

**Comment by mpizenberg** [comment]
So I can confirm that the plugin works if I'm setting the `Prettier Path` config in VSCode to `/home/matthieu/.config/nvm/14.15.5/lib/node_modules/prettier` which indicates it's indeed an issue with the Prettier from the VSCode extension not finding my globally installed (in nvm) plugin. I don't know what to do to change that without having to give it the exact path to the prettier install, which may change if I update my node version with nvm.

I've tried checking the `Prettier: Resolve Global Modules` but it did not make it work.

**Comment by mpizenberg** [comment]
So I guess you can close this issue since it's not really an issue with the plugin. If there is a solution not involving setting the path in the extension config though, it is worth mentioning it in the readme.

**Comment by kachkaev** [comment]
Thanks for sharing your findings @mpizenberg! I think we also faced the same issue with @jwoLondon a few weeks ago and ended up manually defining Prettier location just like you. I had a brief look at the extension code but could not find any obvious suspects so paused the investigation for now.

Would you be interested in creating an issue in https://github.com/prettier/prettier-vscode so that we could investigate it together with the maintainers? The problem should affect not just the Elm plugin, so may get enough attention and eventually get fixed.

I’ll close this issue for now, but will happy to undo this if you’d like to continue the discussion here 🙌
