### ISSUE TITLE
elm-format 0.8.6

### ISSUE THREAD

**Issue by kachkaev** [gicentre/prettier-plugin-elm#42]
Release notes: https://github.com/avh4/elm-format/releases/tag/0.8.6

The plugin uses `elm-format@0.8.5` so we should update the dependency and release a new version.

**Comment by kachkaev** [comment]
@jwoLondon do you foresee any downsides?

**Comment by jwoLondon** [comment]
No downsides. Will be interesting to see if the performance increase is noticeable as we do sometimes deal with very large files that pass through elm-format. Thanks for upgrading.

**Comment by kachkaev** [comment]
I just released [v0.10.0](https://github.com/gicentre/prettier-plugin-elm/releases/tag/v0.10.0) with `elm-format@0.8.6`. Please let me know if you experience any issues!
